config/routes.rb
EvaluateMyIdeas::Application.routes.draw do

  resources :ideas do
    member do
      get 'add_one'
    end
  end

  match 'home' => 'home#index', :as => :home
  root :to => "ideas#index"
  match '*a' => redirect('/')

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  default_scope :order => 'votes DESC'

  protected

    def add_one
      self.votes += 1
      self.save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]

  # GET /ideas
  # GET /ideas.xml
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.xml
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.xml
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.xml
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to(@idea, :notice => 'Idea was successfully created.') }
        format.xml  { render :xml => @idea, :status => :created, :location => @idea }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @idea.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.xml
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to(@idea, :notice => 'Idea was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @idea.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.xml
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to(ideas_url) }
      format.xml  { head :ok }
    end
  end

  # GET /ideas/1/add_one
  def add_one
    @idea = Idea.find(params[:id])
    @num = @idea.add_one() # this returns the number of votes

    respond_to do |format|
      #format.html { @num }
      format.html { redirect_to(ideas_url) }
      format.json { render :json => @num }
    end
  end

  protected

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == "sethorshayne" && password == "AStrongPassword!"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :cols => 60, :rows => 4 %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label :votes %><br />
    <%= f.text_field :votes, :value => 0 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div class="idea-listing">
  <div class="left">
    <div class="title">
      <%= idea.title %>
    </div>
    <div class="description">
      <%= idea.description %>
    </div>
    <% if idea.link %>
    <div class="link">
      Demo: <%= link_to idea.link, idea.link %>
    </div>
    <% end %>
  </div> <!-- div.left -->
  <div class="right">
    <div class="votes">
      <div class="votebox">
        votes
      </div>
      <% if idea.votes > 100 %>
      100+
      <% else %>
      <%= idea.votes %>
      <% end %>
    </div>
    <div class="upvote">
      <%= link_to 'I like it!', idea_path(idea)+'/add_one' %>
    </div>
  </div>
  <br style="clear:both" />
</div> <!-- div.right -->

app/views/ideas/_votes.html.erb
<div>
  <%= idea.votes %>
</div>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<%= render @ideas %>

<br />

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @idea.title %>
</p>

<p>
  <b>Description:</b>
  <%= @idea.description %>
</p>

<p>
  <b>Link:</b>
  <%= @idea.link %>
</p>

<p>
  <b>Votes:</b>
  <%= @idea.votes %>
</p>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evaluate My Ideas</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-latest.min' %>
  <%= javascript_include_tag 'rails' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>

<body>
  <div id="site">
    <div id="header">
      <h1><%= link_to 'Evaluate My Ideas', root_path %> </h1>
    </div> <!-- #header -->

    <div id="yield">
      <%= yield %>
    </div> <!-- #yield -->
    <br style="clear:both"/>

    <div id="footer">
      &copy; <%= link_to 'Evaluate My Ideas', root_path %>. All rights reserved.
    </div> <!-- #footer -->
  </div> <!-- #site -->

</body>
</html>